In [494]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Data Loading and Initial Exploration

In [495]:
raw_data_path = '../Data/raw/Luxury_Housing_Bangalore.csv'

try:
    df = pd.read_csv(raw_data_path)
    print(f"Data loaded successfully!")
    print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
except FileNotFoundError:
    print("ERROR: File not found!")
    print("Please check the filename and path.")

# Display the dataframe
df

Data loaded successfully!
Shape: 101000 rows × 18 columns

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [496]:
print("Columns Summary:")
print(df.describe())

Columns Summary:
       Unit_Size_Sqft  Connectivity_Score  Amenity_Score  \
count    90954.000000       101000.000000   90910.000000
mean      5972.274765            6.992619       7.503663
std       1783.397836            1.731757       1.440758
min         -1.000000            4.000031       5.000224
25%       4477.250000            5.494526       6.260329
50%       5990.000000            6.985805       7.499123
75%       7497.000000            8.490000       8.752207
max       8999.000000            9.999970       9.999865

       Locality_Infra_Score  Avg_Traffic_Time_Min
count         101000.000000         101000.000000
mean               7.498426             67.182921
std                1.443128             30.271611
min                5.000013             15.000000
25%                6.247954             41.000000
50%                7.495614             67.000000
75%                8.749824             93.000000
max                9.999956            119.000000

In [497]:
print("Data Types:")
print(df.dtypes)

Data Types:
Property_ID              object
Micro_Market             object
Project_Name             object
Developer_Name           object
Unit_Size_Sqft          float64
Configuration            object
Ticket_Price_Cr          object
Transaction_Type         object
Buyer_Type               object
Purchase_Quarter         object
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status        object
Sales_Channel            object
NRI_Buyer                object
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments           object
dtype: object

In [498]:
print("Dataset Info:")
print(df.info())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB
None

### Exploring the Dataset

In [499]:
print("Duplicate Rows:")
duplicates = df.duplicated().sum()
print(f"Total duplicates: {duplicates}")

Duplicate Rows:
Total duplicates: 1000

In [500]:
### Removing Duplicates
print("Removing duplicates...")
initial_rows = len(df)
df = df.drop_duplicates()
removed = initial_rows - len(df)
print(f"Removed {removed} duplicate rows")

print(f"Duplicate Rows: {df.duplicated().sum()}")

Removing duplicates...
Removed 1000 duplicate rows
Duplicate Rows: 0

In [501]:
print(f"{df.isnull().sum()}")
missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing_Count': missing,
    'Percentage': missing_percent
})
print(missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False))

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9957
Configuration               0
Ticket_Price_Cr          9913
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64
                 Missing_Count  Percentage
Buyer_Comments           18099      18.099
Amenity_Score            10000      10.000
Unit_Size_Sqft            9957       9.957
Ticket_Price_Cr           9913       9.913

### Cleaning the Dataset

In [502]:
### Cleaning Buyer_Comments...
print("Cleaning Buyer_Comments nulls...")

if 'Buyer_Comments' in df.columns:
    df['Buyer_Comments'] = df['Buyer_Comments'].replace('', np.nan)
    df['Buyer_Comments'] = df['Buyer_Comments'].str.strip()

Cleaning Buyer_Comments nulls...

In [503]:
### Handle Amenity_Score nulls
print("Handling Amenity_Score nulls...")

print(f"Missing Values: {df['Amenity_Score'].isnull().sum()}")

if 'Amenity_Score' in df.columns:
    missing_amenity = df['Amenity_Score'].isnull().sum()
    if missing_amenity > 0:
        median_amenity = df['Amenity_Score'].median() # filling missing values with median
        df['Amenity_Score'].fillna(median_amenity, inplace=True)
        print(f"Filled {missing_amenity} nulls with median: {median_amenity}")
    else:
        print(f"No Missing Values")

print(f"Missing Values: {df['Amenity_Score'].isnull().sum()}")

Handling Amenity_Score nulls...
Missing Values: 10000
Filled 10000 nulls with median: 7.49976649202713
Missing Values: 0

In [504]:
### Standardize Configuration
print(f"Standardize Configuration...")

print(f"Unique Result: {df['Configuration']}")

if "Configuration" in df.columns:
    df['Configuration'] = df['Configuration'].str.strip().str.upper()

print(f"Unique Result: {df['Configuration']}")

Standardize Configuration...
Unique Result: 0         4bhk
1         3Bhk
2         4bhk
3         3BHK
4         4Bhk
         ...
99995    5Bhk+
99996     4Bhk
99997     4BHK
99998     4bhk
99999    5Bhk+
Name: Configuration, Length: 100000, dtype: object
Unique Result: 0         4BHK
1         3BHK
2         4BHK
3         3BHK
4         4BHK
         ...
99995    5BHK+
99996     4BHK
99997     4BHK
99998     4BHK
99999    5BHK+
Name: Configuration, Length: 100000, dtype: object

In [505]:
### Handeling Unit_Size_Sqft column
print(f"Handeling Unit_Size_Sqft column...")

print(f"Missing Unit: {df['Unit_Size_Sqft'].isnull().sum()}")

if "Unit_Size_Sqft" in df.columns:

    negative_unit = (df['Unit_Size_Sqft'] < 0).sum()

    if negative_unit > 0:
        
        df.loc[df['Unit_Size_Sqft'] < 0, 'Unit_Size_Sqft'] = np.nan

        df['Unit_Size_Sqft'] = df.groupby('Configuration')['Unit_Size_Sqft'].transform(lambda x: x.fillna(x.median()))


    missing_unit = df['Unit_Size_Sqft'].isnull().sum()

    if missing_unit > 0:
        df['Unit_Size_Sqft'] = df.groupby('Configuration')['Unit_Size_Sqft'].transform(lambda x: x.fillna(x.median())) 

        print(f"Missing Unit filled with median according to Configuration Column")

print(f"Missing Unit: {df["Unit_Size_Sqft"].isnull().sum()}")

Handeling Unit_Size_Sqft column...
Missing Unit: 9957
Missing Unit: 0

In [506]:
### Cleaning Ticket_Price_Cr Column (FIXED VERSION)

print("Cleaning Ticket_Price_Cr column...")

print(f"\nMissing values BEFORE: {df['Ticket_Price_Cr'].isnull().sum()}")

if "Ticket_Price_Cr" in df.columns:
    
    # Replace all characters EXCEPT: digits (0-9), dot (.), and minus sign (-)
    df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].astype(str).str.replace('[^0-9.-]', '', regex=True)
    
    # Convert to numeric
    df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')
    print(f"Converted to numeric")
    
    # Check for negative values
    print("\nChecking for negative values...")
    negative_price = (df['Ticket_Price_Cr'] < 0).sum()
    print(f"Negative values found: {negative_price}")
    
    if negative_price > 0:        
        # Replace negative values with NaN
        df.loc[df['Ticket_Price_Cr'] < 0, 'Ticket_Price_Cr'] = np.nan
        print(f"Replaced {negative_price} negative values with NaN")
    
    print(f"Checking Negative values: {(df['Ticket_Price_Cr'] < 0).sum()}")

    # Fill missing values using Micro_Market + Configuration
    print("\nFilling missing values...")
    missing_before = df['Ticket_Price_Cr'].isnull().sum()
    print(f"Missing values to fill: {missing_before}")
    
    if missing_before > 0:
        # Fill by Micro_Market + Configuration
        df['Ticket_Price_Cr'] = df.groupby(['Micro_Market', 'Configuration'])['Ticket_Price_Cr'].transform(
            lambda x: x.fillna(x.median())
        )
    
    print(f"\nMissing values AFTER: {df['Ticket_Price_Cr'].isnull().sum()}")

Cleaning Ticket_Price_Cr column...

Missing values BEFORE: 9913
Converted to numeric

Checking for negative values...
Negative values found: 5
Replaced 5 negative values with NaN
Checking Negative values: 0

Filling missing values...
Missing values to fill: 9918

Missing values AFTER: 0

In [507]:
print("Standardize Micro_Market and Developer_Name...")

print(f"Unique before:\n{df[['Micro_Market', 'Developer_Name']].drop_duplicates()}")

if "Micro_Market" in df.columns:
    df['Micro_Market'] = df['Micro_Market'].str.strip().str.upper()

if "Developer_Name" in df.columns:
    df['Developer_Name'] = df['Developer_Name'].str.strip().str.upper()

print(f"Unique after:\n{df[['Micro_Market', 'Developer_Name']].drop_duplicates()}")

Standardize Micro_Market and Developer_Name...
Unique before:
           Micro_Market     Developer_Name
0         Sarjapur Road                RMZ
1           Indiranagar        Puravankara
2     Bannerghatta Road       Tata Housing
3          bellary road            Embassy
4           Koramangala            SNN Raj
...                 ...                ...
2777      SARJAPUR ROAD       Tata Housing
2987        KORAMANGALA            SNN Raj
3430        KORAMANGALA             Godrej
3551    Kanakapura Road            Brigade
4081          JAYANAGAR  Total Environment

[528 rows x 2 columns]
Unique after:
           Micro_Market     Developer_Name
0         SARJAPUR ROAD                RMZ
1           INDIRANAGAR        PURAVANKARA
2     BANNERGHATTA ROAD       TATA HOUSING
3          BELLARY ROAD            EMBASSY
4           KORAMANGALA            SNN RAJ
...                 ...                ...
665   BANNERGHATTA ROAD            SNN RAJ
763              DOMLUR         L&T REALTY
898        BELLARY ROAD             GODREJ
957     KANAKAPURA ROAD  TOTAL ENVIRONMENT
1402             HEBBAL            SNN RAJ

[176 rows x 2 columns]

In [508]:
print("STANDARDIZING TEXT COLUMNS")

# Transaction_Type
if 'Transaction_Type' in df.columns:
    df['Transaction_Type'] = df['Transaction_Type'].str.strip().str.title()
    print(f"\nTransaction_Type: {df['Transaction_Type'].unique()}")

# Buyer_Type
if 'Buyer_Type' in df.columns:
    df['Buyer_Type'] = df['Buyer_Type'].str.strip().str.title()
    print(f"Buyer_Type: {df['Buyer_Type'].unique()}")

# Possession_Status
if 'Possession_Status' in df.columns:
    df['Possession_Status'] = df['Possession_Status'].str.strip().str.title()
    print(f"Possession_Status: {df['Possession_Status'].unique()}")

# Sales_Channel
if 'Sales_Channel' in df.columns:
    df['Sales_Channel'] = df['Sales_Channel'].str.strip().str.title()
    print(f"Sales_Channel: {df['Sales_Channel'].unique()}")

# NRI_Buyer
if 'NRI_Buyer' in df.columns:
    df['NRI_Buyer'] = df['NRI_Buyer'].str.strip().str.title()
    print(f"NRI_Buyer: {df['NRI_Buyer'].unique()}")

print("\n All text columns standardized!")

STANDARDIZING TEXT COLUMNS

Transaction_Type: ['Primary' 'Secondary']
Buyer_Type: ['Nri' 'Other' 'Hni' 'Cxo' 'Startup Founder']
Possession_Status: ['Launch' 'Under Construction' 'Ready To Move']
Sales_Channel: ['Broker' 'Nri Desk' 'Direct' 'Online']
NRI_Buyer: ['Yes' 'No']

 All text columns standardized!

In [509]:
print("CONVERTING PURCHASE_QUARTER TO DATETIME")

if 'Purchase_Quarter' in df.columns:    
    # Convert to datetime
    df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'], errors='coerce')

    print(f"Converted to datetime!")

CONVERTING PURCHASE_QUARTER TO DATETIME
Converted to datetime!

In [510]:
df.head(20)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,Nri,2025-03-31,7.990091,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under Construction,Nri Desk,No,7.723898,106,NaN
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,Hni,2023-12-31,8.131315,8.669227,Ready To Move,Direct,Yes,6.985493,113,Agent was not responsive.
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,Hni,2024-03-31,7.501657,5.720246,Ready To Move,Online,Yes,6.100929,106,Excellent location!
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,Hni,2024-12-31,4.525216,8.609649,Under Construction,Broker,No,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,BRIGADE,4290.0,4BHK,9.820000,Secondary,Hni,2023-09-30,7.936068,7.499766,Launch,Online,No,5.154027,16,Underpriced for location.
6,PROP000007,BANNERGHATTA ROAD,Project_6,PRESTIGE,6776.0,5BHK+,10.896752,Secondary,Other,2025-03-31,8.643117,8.355238,Under Construction,Direct,No,9.791550,74,Too far from my office.
7,PROP000008,WHITEFIELD,Project_7,TOTAL ENVIRONMENT,5763.0,3BHK,9.357539,Secondary,Nri,2025-03-31,6.781306,9.565013,Under Construction,Direct,Yes,9.054713,31,NaN
8,PROP000009,SARJAPUR ROAD,Project_8,PRESTIGE,5815.0,3BHK,12.299449,Secondary,Other,2024-03-31,7.284164,5.580442,Under Construction,Nri Desk,Yes,8.552046,68,NaN
9,PROP000010,JP NAGAR,Project_9,PURAVANKARA,8675.0,4BHK,9.193310,Primary,Cxo,2023-09-30,9.964399,7.759907,Launch,Direct,Yes,8.395691,18,Too far from my office.
10,PROP000011,RAJAJINAGAR,Project_10,GODREJ,8872.0,4BHK,15.221824,Secondary,Cxo,2024-06-30,8.518025,7.499766,Launch,Online,No,9.282135,102,Will buy after possession.
11,PROP000012,SARJAPUR ROAD,Project_11,BRIGADE,8765.0,5BHK+,7.384787,Secondary,Nri,2024-03-31,8.963027,6.938919,Launch,Broker,No,7.461677,52,Will buy after possession.
12,PROP000013,KORAMANGALA,Project_12,SNN RAJ,4606.0,5BHK+,11.042463,Primary,Startup Founder,2024-03-31,9.061520,6.727766,Under Construction,Online,Yes,9.659271,46,Underpriced for location.
13,PROP000014,KORAMANGALA,Project_13,PURAVANKARA,5157.0,3BHK,15.166285,Primary,Other,2023-12-31,9.796266,9.905273,Launch,Online,Yes,6.198853,55,Agent was not responsive.
14,PROP000015,YELAHANKA,Project_14,L&T REALTY,6463.0,4BHK,13.851563,Secondary,Cxo,2024-06-30,7.788085,9.701402,Ready To Move,Nri Desk,No,8.949489,33,Too far from my office.
15,PROP000016,WHITEFIELD,Project_15,L&T REALTY,4814.0,4BHK,70.000000,Primary,Nri,2024-03-31,9.401200,7.499766,Under Construction,Direct,No,9.850165,33,Too far from my office.
16,PROP000017,INDIRANAGAR,Project_16,SNN RAJ,3369.0,5BHK+,9.750865,Secondary,Nri,2023-12-31,6.337616,8.765687,Launch,Direct,No,9.795284,70,Great value for money.
17,PROP000018,YELAHANKA,Project_17,L&T REALTY,6007.0,4BHK,9.045290,Secondary,Cxo,2024-03-31,8.793448,5.186328,Ready To Move,Nri Desk,Yes,9.256085,77,Loved the amenities!
18,PROP000019,YELAHANKA,Project_18,TOTAL ENVIRONMENT,6010.0,5BHK+,7.623657,Primary,Other,2024-12-31,6.111031,6.898634,Ready To Move,Broker,Yes,8.652232,118,Connectivity is poor.
19,PROP000020,RAJAJINAGAR,Project_19,PURAVANKARA,7324.0,3BHK,9.627966,Secondary,Startup Founder,2024-09-30,8.474531,9.658975,Ready To Move,Online,Yes,5.049366,116,Will buy after possession.

In [513]:
df.dtypes

Property_ID                     object
Micro_Market                    object
Project_Name                    object
Developer_Name                  object
Unit_Size_Sqft                 float64
Configuration                   object
Ticket_Price_Cr                float64
Transaction_Type                object
Buyer_Type                      object
Purchase_Quarter        datetime64[ns]
Connectivity_Score             float64
Amenity_Score                  float64
Possession_Status               object
Sales_Channel                   object
NRI_Buyer                       object
Locality_Infra_Score           float64
Avg_Traffic_Time_Min             int64
Buyer_Comments                  object
dtype: object

### Load and Save Cleaned Data

In [514]:
df.info

<bound method DataFrame.info of       Property_ID       Micro_Market Project_Name Developer_Name  \
0      PROP000001      SARJAPUR ROAD    Project_0            RMZ
1      PROP000002        INDIRANAGAR    Project_1    PURAVANKARA
2      PROP000003  BANNERGHATTA ROAD    Project_2   TATA HOUSING
3      PROP000004       BELLARY ROAD    Project_3        EMBASSY
4      PROP000005        KORAMANGALA    Project_4        SNN RAJ
...           ...                ...          ...            ...
99995  PROP099996       BELLARY ROAD  Project_495     L&T REALTY
99996  PROP099997          YELAHANKA  Project_496     L&T REALTY
99997  PROP099998        RAJAJINAGAR  Project_497       PRESTIGE
99998  PROP099999        INDIRANAGAR  Project_498        SNN RAJ
99999  PROP100000        HENNUR ROAD  Project_499        EMBASSY

       Unit_Size_Sqft Configuration  Ticket_Price_Cr Transaction_Type  \
0              4025.0          4BHK        12.750846          Primary
1              5760.0          3BHK        16.292152          Primary
2              7707.0          4BHK        10.517724          Primary
3              6192.0          3BHK         9.396367          Primary
4              7147.0          4BHK        15.345392        Secondary
...               ...           ...              ...              ...
99995          5550.0         5BHK+        10.185193          Primary
99996          3171.0          4BHK        12.272081        Secondary
99997          5599.0          4BHK        13.730179          Primary
99998          7342.0          4BHK        10.363989          Primary
99999          5016.0         5BHK+        10.415617          Primary

            Buyer_Type Purchase_Quarter  Connectivity_Score  Amenity_Score  \
0                  Nri       2025-03-31            7.990091       5.462863
1                Other       2024-06-30            4.839024       7.499766
2                  Hni       2023-12-31            8.131315       8.669227
3                  Hni       2024-03-31            7.501657       5.720246
4                  Hni       2024-12-31            4.525216       8.609649
...                ...              ...                 ...            ...
99995              Nri       2023-12-31            8.379908       7.499766
99996            Other       2023-12-31            4.716304       6.374069
99997  Startup Founder       2023-09-30            6.193347       7.482473
99998              Nri       2024-09-30            9.435646       6.369276
99999  Startup Founder       2024-09-30            5.786292       5.284026

        Possession_Status Sales_Channel NRI_Buyer  Locality_Infra_Score  \
0                  Launch        Broker       Yes              9.212491
1      Under Construction      Nri Desk        No              7.723898
2           Ready To Move        Direct       Yes              6.985493
3           Ready To Move        Online       Yes              6.100929
4      Under Construction        Broker        No              5.312510
...                   ...           ...       ...                   ...
99995  Under Construction        Online       Yes              8.378800
99996              Launch        Broker       Yes              7.025209
99997              Launch      Nri Desk       Yes              8.984990
99998  Under Construction      Nri Desk       Yes              7.634717
99999              Launch        Broker       Yes              6.039943

       Avg_Traffic_Time_Min               Buyer_Comments
0                        18         Loved the amenities!
1                       106                          NaN
2                       113    Agent was not responsive.
3                       106          Excellent location!
4                        18      Too far from my office.
...                     ...                          ...
99995                   109    Underpriced for location.
99996                    20  Great view from 15th floor.
99997                    63                          NaN
99998                    89                          NaN
99999                    95                          NaN

[100000 rows x 18 columns]>

In [512]:
print("Saving The Cleaned Data...")

import os

cleaned_data_dir = '../data/cleaned/'
os.makedirs(cleaned_data_dir, exist_ok=True)

cleaned_data_path = cleaned_data_dir + 'luxury_housing_cleaned.csv'
df.to_csv(cleaned_data_path, index=False)

Saving The Cleaned Data...